
// Types para clientes

export const OBTENER_CLIENTES = 'OBTENER_CLIENTES'
export const AGREGAR_CLIENTES = 'AGREGAR_CLIENTES'
export const CARGAR_CLIENTE = 'CARGAR_CLIENTE'
export const EDITAR_CLIENTE = 'EDITAR_CLIENTE'
export const ELIMINAR_CLIENTE = 'ELIMINAR_CLIENTE'
export const CLIENTE_ERROR = 'CLIENTE_ERROR'


// Types para productos

export const OBTENER_PRODUCTOS = 'OBTENER_PRODUCTOS'
export const AGREGAR_PRODUCTOS = 'AGREGAR_PRODUCTOS'
export const CARGAR_PRODUCTO = 'CARGAR_PRODUCTO'
export const EDITAR_PRODUCTO = 'EDITAR_PRODUCTO'
export const ELIMINAR_PRODUCTO = 'ELIMINAR_PRODUCTO'


// Types para pedidos

export const OBTENER_PEDIDOS = 'OBTENER_PEDIDOS'
export const OBTENER_PRODUCTO = 'OBTENER_PRODUCTO'
export const MODIFICAR_CANTIDAD = 'MODIFICAR_CANTIDAD'
export const ELIMINAR_PRODUCTO_PEDIDO = 'ELIMINAR_PRODUCTO_PEDIDO'
export const CREAR_PEDIDO = 'CREAR_PEDIDO'
export const ELIMINAR_PEDIDO = 'ELIMINAR_PEDIDO'

// Types para las alertas

export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA'
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA'


// Types para auth

export const REGISTRO_EXITOSO = 'REGISTRO_EXITOSO'
export const REGISTRO_ERROR = 'REGISTRO_ERROR'
export const OBTENER_USUARIO = 'OBTENER_USUARIO'
export const LOGIN_EXITOSO = 'LOGIN_EXITOSO'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const CERRAR_SESION = 'CERRAR_SESION'
